# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1b85b918ee3b3f717bd0ebdfe475fc771a2a7b0de0667d886dae6141cdcc6533e63d218a9502f58bd492870cad8591ac5f5a9f09a57175e3f93bf564c1e3fb3

test:
  secret_key_base: 288dddd40f34dfdffa115fa18dc7c6beb0f4c4d111a32c2b8508cd7e73221bdc4fbf4a07721a23b3f597312b69b73167b3eee25e61eede2fcc769e30ffdc9de8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
