# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f072f06f40d2eac12f3dc0755e15040e43a4e14654782526cd7cb3734b82fd9ea22e1918a265559f9a06016d36f54aca41ffb4d85ec78149f7f547218e184261

test:
  secret_key_base: 507ba2dd2586dfc1934d4559957a256e6f8126f62e0e7c895ccffe9cea9e050f6f8a030f345f5da2b8d896ff68e5bb069528e5064dd4e81a1df35b635693f2db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
